FROM node:16-alpine3.11
# FROM node:18-alpine3.15

RUN apk --no-cache add \
      bash \
      git \
      g++ \
      make \
      python3
#      ca-certificates \
#      lz4-dev \
#      musl-dev \
#      cyrus-sasl-dev \
#      openssl-dev \

#RUN apk add --no-cache --virtual .build-deps gcc zlib-dev libc-dev bsd-compat-headers py-setuptools bash

# Create app directory
RUN mkdir -p /usr/local/app

# Move to the app directory
WORKDIR /usr/local/app

# Install node-rdkafka
RUN npm install node-rdkafka
# Copy package.json first to check if an npm install is needed
